[package]
name = "otter"
version = "0.1.0"
authors = ["Simon Heath <icefoxen@gmail.com>"]

[dependencies]
iron = "*"
handlebars-iron = "*"
router = "*"
git2 = "*"
logger = "*"
log = "*"
env_logger = "0.3"
hoedown = "*"
rustc-serialize = "*"