[package]
name = "otter"
version = "0.1.0"
authors = ["Simon Heath <icefoxen@gmail.com>"]

[dependencies]
pencil = "0.3"
#git2 = "*"
log = "*"
env_logger = "0.3"
#hoedown = "*"
#rustc-serialize = "*"
